name: Auto Update README Every 4 Hours

on:
  schedule:
    - cron: '30 4-23/4 * * *'  # Runs 4 hours and 30 minutes after each 4-hour interval
  workflow_dispatch:

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pytz pyyaml

      - name: Run update script
        run: |
          python3 .github/actions/update_readme.py

      - name: Commit changes (if any)
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'cocopuff2u'
          git config --global user.email 'cocopuff2u@yahoo.com'
          git add README.md
          git commit -m "Auto Updating README File" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git
