name: Auto Update MacOS XML Every 4 Hours

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pytz pyyaml

      - name: Run update script
        run: |
          python3 .github/actions/generate_macos_appstore_latest.py

      - name: Commit changes (if any)
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'cocopuff2u'
          git config --global user.email 'cocopuff2u@yahoo.com'
          git add latest_raw_files/macos_appstore_latest.xml latest_raw_files/macos_appstore_latest.yaml latest_raw_files/macos_appstore_latest.json
          git commit -m "Auto updating app XML, YAML, JSON files" || echo "No changes to commit"
          git push https://github-actions[bot]:$TOKEN@github.com/cocopuff2u/macadmins_msft.git
